### ISSUE TITLE
Tere se saluda a si misma

### ISSUE THREAD

**Issue by JuanjoSalvador** [juandjara/TereGramBot#17]
Cuando entra en un grupo, detecta que ha entrado un usuario nuevo (posiblemente cosas del API de Telegram), y se saluda a si misma. No entra en bucle, pero sería más correcto que saludase al grupo, no un "illo que pasa @TereGramBot"

Esto es subsanable comprobando que el usuario que entra nuevo no sea ella.

**Comment by juandjara** [comment]
Puedes poner una PR para solventar esto :)

**Comment by JuanjoSalvador** [comment]
Pero primero habrá que abrirte una issue bonica indicando que el problema está ahí y que lo voy a arreglar, ¿no? PROTOCOLO

**Comment by juandjara** [comment]
Puede usted arreglar, señor del protocolo

**Comment by IhToN** [comment]
Refix en
https://github.com/juandjara/TereGramBot/commit/8f5fbf2e830fb7438e0f580cb0ea1c74ba2c3161

**Comment by juandjara** [comment]
Closed by #22
